__version__ = "2.0.0"
__author__ = "Muhammad Akmal"
__email__ = "19624235@mahasiswa.itb.ac.id"
__description__ = "Sisi klien untuk menampilkan GUI Admin dan User."
__license__ = "MIT"
__url__ = "https://github.com/m-akma1/WI1102-Main_Project/tree/main/project-2"
